FROM python:3.12-slim as backend

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend /app/backend
COPY ./main.py /app/main.py

EXPOSE 8000

CMD ["python", "main.py"]
